#ifndef REPROMATIC_RESOURCE_H
#define REPROMATIC_RESOURCE_H

#define IDR_REPROMATIC_MENU 100

#define IDM_FILE_CLOSE WM_APP + 1

#define IDB_OVERVIEW_ICON_16 1000
#define IDB_OVERVIEW_ICON_32 1010

#define ROBOTO_REGULAR 10000
#define ROBOTO_BOLD 10010

#endif
