#ifndef REPROMATIC_RESOURCE_H
#define REPROMATIC_RESOURCE_H

#define IDB_DEFAULT 100
#define IDB_SUMMARY 200
#define IDB_SUMMARY_SIMPLE 201
#define IDB_DIVIDER 210
#define IDB_EXTRACT 220
#define IDB_SORT 230
#define IDB_SORT_RECURSIVE 231

#endif
